# Generated by Django 2.1.1 on 2018-10-20 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknow', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('register_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknow', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subjectfield',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='field',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectField'),
        ),
        migrations.AddField(
            model_name='student',
            name='choose_subjects',
            field=models.ManyToManyField(related_name='interested_students', to='subjects.Subject'),
        ),
    ]
